apiVersion: v1
kind: Service
metadata:
  name: calcbackend
  labels:
    name: calcbackend
    app: calculator  
spec:
  ports:
  - port: 80
    name: calcbackend
    targetPort: 3001
  selector:
    name: calcbackend
    app: calculator